# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dec 03
tagline:          setep forward
url:              
paginate:         1
baseurl:          /
author:
  name:           
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           http://lightder.github.io/

# markdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# page
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
