# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dec 03
tagline:          setep forward
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           http://lightder.github.io/
