# Permalinks
permalink:        pretty

# Setup
title:            June 18
tagline:          step forward
url:
paginate:         5
baseurl:          /
author:
  name:
  url:
  email:

# Custom vars
version:          1.0.0
github:
  repo:           http://lightder.github.io/

# markdown
markdown: kramdown

plugins: ["jekyll-paginate"]

# page
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
